name: "Assignment Checker"
description: "Check assignment"
inputs:
  who-to-greet:
    description: "who"
    required: true
    default: 'World'
    outputs:
      time:
        descriotion "current time"
      runs:
        using: 'docker'
        image: 'Dockerfile'
        args:
          -${{inputs.who-to-greet}}
